version: '3'

name: news-api-demo

services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  news-api:
    container_name: news_api
    image: news-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_PROFILE=demo
    depends_on:
      postgres:
        condition: service_started
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
