version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql